### PR TITLE
Fix div using wrong class attribute on body component

### LINKED ISSUE #20: Body component has div with class attriibute that throws an error
Body component has <code>div</code> with <code>class</code> attriibute that throws an error.

Needs to be replaced with <code>className</code>

### PR DESCRIPTION
**Pull request by franciscoemanuel**
Resolves #20

### CODE REVIEW

File: src/components/Body.js [hunk 1]
```diff
@@ -1,10 +1,9 @@
-import React from "react";
```
Comment (kbrock84) [inline src/components/Body.js]: Please keep double quotes <code>"</code>

File: src/components/Body.js [hunk 2]
```diff
@@ -1,10 +1,9 @@
...
+import React from 'react';
 
 const Body = props => {
-
   return (
     <div className="bg-light">
-      <div class="body">
+      <div className="body">
```
Comment (kbrock84) [inline src/components/Body.js]: Looks great. Thanks!

File: src/components/Body.js (hunk 1 above)
Comment (franciscoemanuel) [reply src/components/Body.js]: Fixed.
